project:
  type: website
  output-dir: docs

website:
  title: "Ittisak Promma"
  navbar:
    left:
      - href: index.qmd
        text: Profile
      - href: education.qmd
        text: Education
      - href: publications.qmd
        text: Publications
    right:
      - icon: envelope
        href: mailto:itpromma@outlook.com
  page-footer:
    left: "© Ittisak Promma"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    smooth-scroll: true
