---
title: "Lectures"
date: last-modified
date-format: "MMM D, YYYY"
---

## Lecture notes

| Lecture | Topic | Files |
|---:|---|---|
| 1 | Introduction to process modeling | Coming soon |
| 2 | Thermodynamics I: Thermodynamic properties | [Lecture 1](lecture-1/lecture-1.qmd) |
| 3 | Thermodynamics II: Pure Fluid | [Lecture 2](lecture-2/lecture-2.qmd) |
| 4 | Thermodynamics III: Mixture | Coming soon |
| 5 | Energy balances of multicomponent systems | Coming soon |
| 6 | Mixer and splitter models | Coming soon |
| 7 | Thermodynamics IV: Vapor-liquid equilibrium | Coming soon |
| 8 | Flash calculations I: Simplified flash calculations | Coming soon |
| 9 | Flash calculations II: Rigorous flash calculations | Coming soon |
| 10 | Distillation I: Simplified distillation calculations | Coming soon |
| 11 | Distillation II: Rigorous distillation calculations | Coming soon |
| 12 | Fixed-conversion and kinetic-based reactor models | Coming soon |
| 13 | Thermodynamics V: Chemical reaction equilibrium | Coming soon |
| 14 | Equilibrium-based reactors | Coming soon |
| 15 | Sequential modular approach for process simulation | Coming soon |
| 16 | Equation-oriented approach for process simulation | Coming soon |
| 17 | Process optimization | Coming soon |
| 18 | Hybrid modeling for process simulation | Coming soon |